### ISSUE TITLE
Background noise removal verification

### ISSUE THREAD

**Issue by mihaiboldeanu** [OceanStreamIO/oceanstream#131]
When applying background noise removal with the following parameters:
`
       "remove_background_noise": {
        "ping_num": 40,
        "range_sample_num": 10,
        "noise_max": -125,
        "SNR_threshold": 3,
        }
`
We lose around 60-65% of data as noise. 
This should be investigated to make sure we arent eliminating to much useful data.

**Comment by simedroniraluca** [comment]
## Parameters Analysis

The background noise detection implemented in `oceanstream` is based on the `remove_noise` function from the echopype library, which in turn is based on the techniques described in the article by **De Robertis & Higginbottom (2007), titled 'A post-processing technique to estimate the signal-to-noise ratio and remove echosounder background noise,' published in the ICES Journal of Marine Sciences (64(6): 1282–1291)**. 

The parameters for `oceanstream`'s `apply_remove_background_noise` function, designed to address background noise issues, are as follows:

- `ds_Sv`: xr.Dataset
    - Dataset containing Sv and echo_range [m].
- `ping_num`: int, default=40
    - Number of pings to obtain noise estimates.
- `range_sample_num`: int, optional
    - Number of samples along the `range_sample` dimension to obtain noise estimates. If not provided, it's computed based on a 10-meter vertical bin for each channel, and the minimum value is used.
- `noise_max`: float, default=-125
    - The upper limit for background noise expected under the operating conditions (default=-125 dB).
- `SNR_threshold`: float, default=3 [dB]
    - Acceptable signal-to-noise ratio.

The default values for the parameters in `oceanstream`'s `apply_remove_background_noise` were chosen based on the default values tested in the article for `calibrated Simrad EK60 echosounders operating at 18, 38, 120, and 200 kHz`:
- Horizontal cell size of 40 pings
- Vertical cell size corresponding to a 10-m vertical bin
- An acceptable signal-to-noise ratio defaulting to 3 dB
- Noise max = -125 dB 

Other important considerations highlighted in the article that should be taken into account when adjusting the input parameters for the `apply_remove_background_noise` include:

- It is advisable that the **`SNR_threshold` be greater than 0**.
- `noise_max` represents an upper limit for background noise expected under the operating conditions. It must be determined empirically and will depend on the echosounder. In the examples presented in the article, `noise_max` was set at **-125 dB** at all frequencies, and this value was never exceeded.
- 'The magnitude and the variability of the noise estimates rapidly level off as increasing numbers of pings are averaged, indicating that they are relatively insensitive to grid size when **more than 20 pings are averaged**, and **10-m deep cells are used**. As a compromise between the stability of the noise estimate and the ability to compensate for rapidly changing noise levels, cell-size parameters of **N = 40** pings in the horizontal and **M corresponding to a 10-m vertical bin in the vertical** were used in the analyses.'

**Comment by simedroniraluca** [comment]
## Analysis of EK80 Dataset with Background Noise Removal

**Raw Dataset Details**:
- Data Source: EK80 raw data - nice data D20190925-T133707.raw - [link](https://noaa-wcsd-pds.s3.amazonaws.com/index.html#data/raw/Pisces/PC1905/EK80/)
- Raw File Size: 46.3 Megabytes (MB)

## Background noise removal applied on processed dataset, after the interpolation step

**Parameters:**
```python
process_parameters = {
        "remove_background_noise": {
        "ping_num": 40,
        "noise_max": -125,
        "SNR_threshold": 3,
    },

}
```

**Proportion of Valid Samples Before Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.62053445

**Proportion of Valid Samples After Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.55701218



![Image](https://github.com/OceanStreamIO/oceanstream/assets/92971445/0dbdd7f3-1040-4b69-96a4-9fb3f85a36a8)

**Comment by simedroniraluca** [comment]
## Analysis of EK80 Dataset with Background Noise Removal

**Raw Dataset Details**:
- Data Source: EK80 raw data - nice data D20190925-T133707.raw - [link](https://noaa-wcsd-pds.s3.amazonaws.com/index.html#data/raw/Pisces/PC1905/EK80/)
- Raw File Size: 46.3 Megabytes (MB)

## Background noise removal applied on processed dataset, after the interpolation step

**Parameters:**
```python
process_parameters = {
        "remove_background_noise": {
        "ping_num": 40,
        "noise_max": -125,
        "SNR_threshold": 0,
    },

}
```

**Proportion of Valid Samples Before Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.62053445

**Proportion of Valid Samples After Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.57064969



![Image](https://github.com/OceanStreamIO/oceanstream/assets/92971445/b1855712-1d11-481d-b630-db3ab2c7c3ba)

**Comment by simedroniraluca** [comment]
## Analysis of EK80 Dataset with Background Noise Removal

**Raw Dataset Details**:
- Data Source: EK80 raw data - nice data D20190925-T133707.raw - [link](https://noaa-wcsd-pds.s3.amazonaws.com/index.html#data/raw/Pisces/PC1905/EK80/)
- Raw File Size: 46.3 Megabytes (MB)

## Background noise removal applied on processed dataset, after the interpolation step

**Parameters:**
```python
process_parameters = {
        "remove_background_noise": {
        "ping_num": 40,
        "range_sample_num": 10,
        "noise_max": -125,
        "SNR_threshold": 3,
    },

}
```

**Proportion of Valid Samples Before Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.62053445

**Proportion of Valid Samples After Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.56191428



![Image](https://github.com/OceanStreamIO/oceanstream/assets/92971445/c71bd081-625a-442f-964c-f66aa71a4148)

**Comment by simedroniraluca** [comment]
## Analysis of EK60 Dataset with Background Noise Removal

**Raw Dataset Details**:
- **Bucket Name:** `ncei-wcsd-archive`
- **Base Path:** `data/raw/Bell_M._Shimada/SH1707/EK60/`
- **Filename:** `Summer2017-D20170620-T011027.raw`
- **Raw File Size:** 26.2  Megabytes (MB)

## Background noise removal applied on processed dataset, after the interpolation step

**Parameters:**
```python
process_parameters = {
        "remove_background_noise": {
        "ping_num": 40,
        "noise_max": -125,
        "SNR_threshold": 3,
    },

}
```

**Proportion of Valid Samples Before Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.85527214

**Proportion of Valid Samples After Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.68439682




![Image](https://github.com/OceanStreamIO/oceanstream/assets/92971445/33476e5a-663f-4892-84b7-a8ed1a1f3677)

**Comment by simedroniraluca** [comment]
## Analysis of EK60 Dataset with Background Noise Removal

**Raw Dataset Details**:
- **Bucket Name:** `ncei-wcsd-archive`
- **Base Path:** `data/raw/Bell_M._Shimada/SH1707/EK60/`
- **Filename:** `Summer2017-D20170620-T011027.raw`
- **Raw File Size:** 26.2  Megabytes (MB)

## Background noise removal applied on processed dataset, after the interpolation step

**Parameters:**
```python
process_parameters = {
        "remove_background_noise": {
        "ping_num": 40,
        "noise_max": -125,
        "SNR_threshold": 0,
    },

}
```

**Proportion of Valid Samples Before Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.85527214

**Proportion of Valid Samples After Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.72555448

![Image](https://github.com/OceanStreamIO/oceanstream/assets/92971445/3216d77e-5ced-4c7b-b78b-1d9c99c2f48c)

**Comment by simedroniraluca** [comment]
## Analysis of EK60 Dataset with Background Noise Removal

**Raw Dataset Details**:
- **Bucket Name:** `ncei-wcsd-archive`
- **Base Path:** `data/raw/Bell_M._Shimada/SH1707/EK60/`
- **Filename:** `Summer2017-D20170620-T011027.raw`
- **Raw File Size:** 26.2  Megabytes (MB)

## Background noise removal applied on unprocessed dataset (raw data):

**Parameters:**
```python
process_parameters = {
        "ping_num": 40,
        "noise_max": -125,
        "SNR_threshold": 3,
    },

}
```

**Proportion of Valid Samples Before Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.9971564

**Proportion of Valid Samples After Background Noise Removal:**
- (Valid Samples) / (Total Samples): 0.62754032



![Image](https://github.com/OceanStreamIO/oceanstream/assets/92971445/0daaedc1-87b4-408d-99ad-6ace50ecc887)

**Comment by simedroniraluca** [comment]
**Conclusion:**

- After a thorough analysis, it has become evident that applying background noise removal is more effective after the interpolation step in the processed dataset. When the background noise removal function is applied to an unprocessed dataset, as demonstrated in the example above, approximately 36% of the data is invalidated. This significant loss of data underscores the importance of the sequence in which processing steps are applied.

- Adjusting the `threshold_SNR` parameter can affect the proportion of invalidated samples. Decreasing the `threshold_SNR` leads to a reduction in invalidated samples; however, it is not advisable to set it below 0.

- The parameter `range_sample_num`, which determines the number of samples along the `range_sample` dimension for noise estimation: 
    - When not explicitly provided, it's computed based on a 10-meter vertical bin for each channel, with the minimum value being used. This default computation seems to be effective in most cases.

- In the examples analyzed, different configurations of parameters were applied to a processed dataset. The percentage of invalidated data in these scenarios ranged between 5-17%, which is significantly lower than that observed in the unprocessed dataset. Based on these findings, it is recommended to use the default parameters for background noise removal in future analyses.
