### ISSUE TITLE
Add __init__ to package modules for easier imports

### ISSUE THREAD

**Issue by mihaiboldeanu** [OceanStreamIO/oceanstream#91]
As a user of the oceasntream package i want to be able to easily and cleanly import functions from the modules.

Tasks:

 - [x] Add __init__ for all modules
 - [x] Add __init__ for entire package
 - [x] Test and fix test in case of failures

**Comment by beatfactor** [comment]
Should make it easy to use the `oceanstream` library in the IoT Edge module, which is available here: https://github.com/OceanStreamIO/iotedge-echosounder
